### ISSUE TITLE
Interface to access nodes arrow-linked to another node seems to be missing

### ISSUE THREAD

**Issue by kraghuprasad** [nnako/freeplane-python-io#8]
I am writing a tool to convert a freeplane mindmap into a well-formatted PDF. I needed to create section-links in the PDF based on the arrow-links present in the mindmap. While going through the documentation, I am still unable to find a property or method which can give me all the nodes to which a node is pointing to using arrow-links. Similarly.

Similarly I also need the list of nodes which is referring to a particular node (to which the arrows terminate).

Is it possible using freeplane-python-io?

**Comment by nnako** [comment]
Hi @kraghuprasad and thank you for your request.

Unfortunately, arrow links can currently only be **added** to a specific node using the node's method `add_arrowlink()`. And this arrow link will always be an outgoing link. Other methods have not been implemented concerning arrow links, yet.

The ideas for methods are:

- `<node>.arrowlinks` to retrieve a list of nodes which are arrow-connected from the `<node>`
- `<node>.arrowlinked` to retrieve a list of nodes which are arrow-linking the `<node>` (incoming arrows)
- `<node>.del_arrowlink( <idx> )` to remove an existing outgoing arrow link. `<idx>` will have to start from `0` and would be respecting the sequence returned by the `arrowlinks` method.

Would these methods be a solution for you?

**Comment by nnako** [comment]
I just pushed the implementation of the two methods:

- `<node>.arrowlinks` to retrieve a list of nodes which are arrow-connected from the `<node>`
- `<node>.arrowlinked` to retrieve a list of nodes which are arrow-linking the `<node>` (incoming arrows)

the last method will follow when I got time again ;-) . If you are able to update the source code or if you were running the sources anyway (not installing via pip), you can update your sources and try the solution. If you installed using pip, you will have to wait for the next "official" release, which may come very soon.

**Comment by nnako** [comment]
uploaded release **0.10.0** containing the new arrowlink attributes and methods. closing this issue.

**Comment by kraghuprasad** [comment]
Sorry for the delayed response, as I am on vacation and Net-access is not a
strong point for this place.

The two properties node.arrowlinks and node.arrowlinked seem to be perfect
for me right now.
I'll check them out soon. What I needed was a list of nodes to which
outgoing arrows point to, from
the source-node; and a list of the same from where incoming ones land up on
the chosen node.
From that angle, the names seem perfect.

regards,
Raghu

**Comment by kraghuprasad** [comment]
I would like to confirm that the newly added features of accessing arrow-linked nodes are working perfectly.

Thanks.
